### ISSUE TITLE
Endpoint to query entities

### ISSUE THREAD

**Issue by dariok** [dariok/wdbplus#131]
Abfragen:
- Liste aller Einträge zu einem Typ mit Normdaten-ID
- strukturierte Angaben zu einer (Normdaten-)ID oder Namensansetzung (Auslieferung Eintrag in listPerson, listPlace, listOrg, listBibl) – Suche mit Anfangsbuchstaben ermöglichen für Abfrage im Word-Plugin!
- Ausgabe aller Fundstellen (Link auf EE mit Stelle)

**Comment by dariok** [comment]
see also https://github.com/KONDE-AT/dsebaseapp/blob/master/modules/api.xql

**Comment by csae8092** [comment]
just noticed that module imports some variables from another module (e.g. $app:data) and one function app:getDocName (which is anyhow stupid because it does exatly the same as utils:get-doc-name (or how this function is called exactly...)
