### ISSUE TITLE
Functions that catch errors and format them using wdbErr:error fail if they specify item() as return

### ISSUE THREAD

**Issue by simar0at** [dariok/wdbplus#343]
Example
```
exerr:ERROR The actual return type does not match the sequence type declared in the function's signature: wdb:populateModel(xs:string, xs:string, map(*)) item()
Expected cardinality: exactly one, got 2. [at line 195, column 35, source: /db/apps/edoc/modules/function.xqm]
In function: wdb:populateModel(xs:string, xs:string, map(*)) [25:15:/db/apps/edoc/modules/app.xqm].
The actual return type does not match the sequence type declared in the function's signature: wdb:populateModel(xs:string, xs:string, map(*)) item(). Expected cardinality: exactly one, got 2.
```
wdbErr:error returns **two** items. (`<head/>`,`<body>`)
Wrap them in `<html>` or provide one map?

**Comment by dariok** [comment]
See also #336

**Comment by dariok** [comment]
wrapping in `<html>` is not possible: the frame has already been provided by the templating system.

**Comment by dariok** [comment]
There are 2 basic points of failure:

1. wdb:populateModel or wdbfp:start – as these errors occur before the templating system has created anything, there is no HTML
2. other places (e. g. wdbPF:*) – these can occur when the outermost parts and html:head have already been created by the templating system.
