### ISSUE TITLE
When installung as wdb:wdbusers exist-db asks for username:password

### ISSUE THREAD

**Issue by simar0at** [dariok/wdbplus#344]
Steps to reproduce
* eXgit install script running as dedicated wdb user (eXide login as wdb)
* Try accessing http://localhost:8080/exist/apps/edoc/index.html (or start.html)

Wrong behaviour
* Browsers prompt for a login (wdb for example works)

Correct behaviour
* It should just respond with an html page.
* use private mode, browsers cache the login credetials

**Comment by dariok** [comment]
Making necessary files world readable (see #346), should solve this.
