### ISSUE TITLE
[annotation] annotated entities should not be rendered as <a> tags

### ISSUE THREAD

**Issue by simar0at** [dariok/wdbplus#428]
Links/<a> tags have a problematic behavior when trying to select text within them. They can be dragged as a whole and so interacting with the mouse is counter intuitive.

**Comment by dariok** [comment]
In general, this is up to the XSLT generating the view so it may be project specific.

From a semantics view, `button` would be a better choice as it is not an external link. I do not know, though, whether text selection works better on buttons.

**Comment by dariok** [comment]
This has been changed in local project files and additionally incorporated into the example XSLTs and view.css.

Text in buttons is styled as selectable.

**Comment by simar0at** [comment]
Works much better now for annotation.
